// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProtocoloTeste.Models;

#nullable disable

namespace ProtocoloTeste.Migrations
{
    [DbContext(typeof(ProtocoloDbContext))]
    partial class ProtocoloDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProtocoloTeste.Models.Cliente", b =>
                {
                    b.Property<int>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCliente"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdCliente");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("ProtocoloTeste.Models.Protocolo", b =>
                {
                    b.Property<int>("IdProtocolo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProtocolo"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataAbertura")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataFechamento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ProtocoloStatusId")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("IdProtocolo");

                    b.HasIndex("ClienteId");

                    b.HasIndex("ProtocoloStatusId");

                    b.ToTable("Protocolos");
                });

            modelBuilder.Entity("ProtocoloTeste.Models.ProtocoloFollow", b =>
                {
                    b.Property<int>("IdFollow")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFollow"));

                    b.Property<DateTime>("DataAcao")
                        .HasColumnType("datetime2");

                    b.Property<string>("DescricaoAcao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ProtocoloId")
                        .HasColumnType("int");

                    b.HasKey("IdFollow");

                    b.HasIndex("ProtocoloId");

                    b.ToTable("ProtocoloFollows");
                });

            modelBuilder.Entity("ProtocoloTeste.Models.StatusProtocolo", b =>
                {
                    b.Property<int>("IdStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdStatus"));

                    b.Property<string>("NomeStatus")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdStatus");

                    b.ToTable("StatusProtocolos");
                });

            modelBuilder.Entity("ProtocoloTeste.Models.Protocolo", b =>
                {
                    b.HasOne("ProtocoloTeste.Models.Cliente", "Cliente")
                        .WithMany("Protocolos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProtocoloTeste.Models.StatusProtocolo", "ProtocoloStatus")
                        .WithMany()
                        .HasForeignKey("ProtocoloStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("ProtocoloStatus");
                });

            modelBuilder.Entity("ProtocoloTeste.Models.ProtocoloFollow", b =>
                {
                    b.HasOne("ProtocoloTeste.Models.Protocolo", "Protocolo")
                        .WithMany("ProtocoloFollows")
                        .HasForeignKey("ProtocoloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Protocolo");
                });

            modelBuilder.Entity("ProtocoloTeste.Models.Cliente", b =>
                {
                    b.Navigation("Protocolos");
                });

            modelBuilder.Entity("ProtocoloTeste.Models.Protocolo", b =>
                {
                    b.Navigation("ProtocoloFollows");
                });
#pragma warning restore 612, 618
        }
    }
}
